version: "3.3"

services:
    web:
        container_name: cicd_web
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./server.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-blue
            - php-green

    php-blue:
        container_name: cicd_php_blue
        image: pirojok/cicd-learn:latest
        depends_on:
            - rabbitmq

    php-green:
        container_name: cicd_php_green
        image: pirojok/cicd-learn:latest
        depends_on:
            - rabbitmq

    rabbitmq:
        container_name: cicd_rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq/

volumes:
    rabbitmq_data:
        driver:
            local
