name: Deployment

on:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    deployment:
        runs-on: macos-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v3
        -   name: Set up QEMU
            uses: docker/setup-qemu-action@v3
        -   name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
        -   name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        -   name: Build and push
            uses: docker/build-push-action@v5
            with:
                file: .docker/php/Dockerfile
                push: true
                tags: pirojok/cicd-learn:latest
